import { z } from 'zod';
export const id = z.uuid();
export const date = z.iso.date();
export const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/);
export const timezone = z.string().refine(v => { try { new Intl.DateTimeFormat('en',{timeZone:v}); return true; } catch { return false; } }, 'Use an IANA timezone');
const text = (n = 200) => z.string().trim().min(1).max(n);
const nullableText = (n = 200) => text(n).nullable();
const url = z.url().refine(v => ['https:','http:'].includes(new URL(v).protocol), 'Use HTTP or HTTPS').nullable();
export const taskTypes = ['assignment','homework','quiz','exam','midterm','final','project','lab','reading','presentation','other'] as const;
export const policyTypes = ['attendance','late_work','makeup_work','grading','extra_credit','office_hours','other'] as const;
export const profileInput = z.object({display_name:text(100),timezone}).strict();
export const onboardingInput = profileInput.extend({semester_name:text(120)});
export const semesterInput = z.object({name:text(120),start_date:date.nullable().default(null),end_date:date.nullable().default(null),archived_at:z.iso.datetime({offset:true}).nullable().default(null)}).strict().refine(v=>!v.start_date||!v.end_date||v.start_date<=v.end_date,{message:'End date must follow start date'});
export const courseInput = z.object({semester_id:id,name:text(),code:nullableText().default(null),section:nullableText().default(null),instructor_name:nullableText().default(null),instructor_email:z.email().nullable().default(null),location:nullableText().default(null),color:z.string().regex(/^#[0-9a-f]{6}$/i).default('#436b52'),course_url:url.default(null)}).strict();
export const meetingInput = z.object({course_id:id,day_of_week:z.number().int().min(0).max(6),start_time:time,end_time:time,location:nullableText().default(null),start_date:date.nullable().default(null),end_date:date.nullable().default(null)}).strict().refine(v=>v.end_time>v.start_time,{message:'End time must follow start time'}).refine(v=>!v.start_date||!v.end_date||v.end_date>=v.start_date,{message:'Invalid meeting date range'});
export const taskFields = z.object({title:text(300),description:nullableText(10000).default(null),task_url:url.default(null),course_id:id.nullable().default(null),type:z.enum(taskTypes).default('assignment'),status:z.enum(['pending','completed','cancelled']).default('pending'),deadline_type:z.enum(['none','date_only','exact_time']).default('none'),due_date:date.nullable().default(null),due_at:z.iso.datetime({offset:true}).nullable().default(null),points_possible:z.number().min(0).nullable().default(null),weight_percent:z.number().min(0).max(100).nullable().default(null),estimated_minutes:z.number().int().positive().nullable().default(null),priority:z.number().int().min(0).max(3).default(0)}).strict();
export const validDeadline = (v:{deadline_type:string;due_date:string|null;due_at:string|null}) => v.deadline_type==='none' ? !v.due_date&&!v.due_at : v.deadline_type==='date_only' ? !!v.due_date&&!v.due_at : !!v.due_at&&!v.due_date;
export const taskInput = taskFields.refine(validDeadline,{message:'Deadline fields must match deadline type'});
export type TaskInput = z.infer<typeof taskInput>;
export type Task = TaskInput & {id:string;owner_id:string;completed_at:string|null;created_at:string;updated_at:string;source_type:string;source_document_id:string|null;source_page:number|null;source_excerpt:string|null;confidence:string|null};
export type Course = z.infer<typeof courseInput> & {id:string};
export type Semester = z.infer<typeof semesterInput> & {id:string};
export type Meeting = z.infer<typeof meetingInput> & {id:string};
export const provenance = {source_page:z.number().int().positive().nullable(),source_excerpt:z.string().max(2000).nullable(),confidence:z.enum(['high','medium','low'])};
// Model outputs require explicit nullable fields rather than inferred/defaulted values.
export const extractedCourse = z.object({name:nullableText(),code:nullableText(),section:nullableText(),instructor_name:nullableText(),instructor_email:z.email().nullable(),location:nullableText()});
export const extractedMeeting = z.object({day_of_week:z.number().int().min(0).max(6),start_time:time,end_time:time,location:nullableText(),start_date:date.nullable(),end_date:date.nullable()});
export const extractedTask = z.object({title:text(300),description:nullableText(10000),type:z.enum(taskTypes),deadline_type:z.enum(['none','date_only','exact_time']),due_date:date.nullable(),due_at:z.iso.datetime({offset:true}).nullable(),points_possible:z.number().min(0).nullable(),weight_percent:z.number().min(0).max(100).nullable()});
export const extractedGrading = z.object({name:text(),weight_percent:z.number().min(0).max(100).nullable()});
export const extractedPolicy = z.object({policy_type:z.enum(policyTypes),title:text(),content:text(10000)});
export const extractionSchema = z.object({course:extractedCourse.extend(provenance).nullable(),meetings:z.array(extractedMeeting.extend(provenance)).max(50),tasks:z.array(extractedTask.extend(provenance)).max(300),grading:z.array(extractedGrading.extend(provenance)).max(50),policies:z.array(extractedPolicy.extend(provenance)).max(50)});
export const candidateSchemas = {course:extractedCourse,meeting:extractedMeeting.refine(v=>v.end_time>v.start_time && (!v.start_date||!v.end_date||v.end_date>=v.start_date),'Invalid meeting range'),task:extractedTask.refine(validDeadline,'Invalid deadline'),grading_component:extractedGrading,policy:extractedPolicy};
export type EntityType = keyof typeof candidateSchemas;
export type Candidate = {id:string;entity_type:EntityType;candidate_data:Record<string,unknown>;source_page:number|null;source_excerpt:string|null;confidence:'high'|'medium'|'low';accepted:boolean;edited:boolean};
export const reviewInput = z.object({candidate_id:id,candidate_data:z.record(z.string(),z.unknown()),accepted:z.boolean()}).strict();
export type ApiError = {error:{code:string;message:string;request_id:string;issues?:unknown}};
