import { Temporal } from '@js-temporal/polyfill';
import type { Task, Meeting, Course, Semester } from './contracts';
export function todayIn(zone:string, now=new Date()) { return Temporal.Instant.from(now.toISOString()).toZonedDateTimeISO(zone).toPlainDate().toString(); }
export function localToInstant(day:string, time:string, zone:string) { return Temporal.ZonedDateTime.from(`${day}T${time}[${zone}]`,{disambiguation:'reject'}).toInstant().toString(); }
export function dueDay(t:Pick<Task,'deadline_type'|'due_date'|'due_at'>,zone:string) { return t.deadline_type==='date_only'?t.due_date:t.due_at?todayIn(zone,new Date(t.due_at)):null; }
export function isOverdue(t:Task,zone:string,now=new Date()) { return t.status==='pending' && (t.deadline_type==='date_only' ? !!t.due_date&&t.due_date<todayIn(zone,now) : t.deadline_type==='exact_time'&&!!t.due_at&&new Date(t.due_at)<now); }
export function deadlineMs(t:Task,zone:string) { return t.due_at?Date.parse(t.due_at):t.due_date?Number(Temporal.PlainDate.from(t.due_date).add({days:1}).toZonedDateTime(zone).epochMilliseconds):Infinity; }
export function rankTasks(tasks:Task[],zone:string,now=new Date()) { const exam=new Set(['exam','midterm','final']);return [...tasks].sort((a,b)=>Number(isOverdue(b,zone,now))-Number(isOverdue(a,zone,now)) || (deadlineMs(a,zone)-deadlineMs(b,zone)||0) || b.priority-a.priority || Number(exam.has(b.type))-Number(exam.has(a.type)) || a.title.localeCompare(b.title)||a.id.localeCompare(b.id)); }
export function dashboard(tasks:Task[],zone:string,now=new Date()) {const today=todayIn(zone,now),day=Temporal.PlainDate.from(today); const sorted=rankTasks(tasks,zone,now); const pending=sorted.filter(t=>t.status==='pending');return {today:pending.filter(t=>dueDay(t,zone)===today),do_now:pending.filter(t=>isOverdue(t,zone,now)||dueDay(t,zone)===today),overdue:pending.filter(t=>isOverdue(t,zone,now)),up_next:pending.filter(t=>{const d=dueDay(t,zone);return d&&d>today&&d<=day.add({days:3}).toString();}),due_soon:pending.filter(t=>{const d=dueDay(t,zone);return d&&d>day.add({days:3}).toString()&&d<=day.add({days:14}).toString();}),later:pending.filter(t=>{const d=dueDay(t,zone);return d&&d>day.add({days:14}).toString();}),unscheduled:pending.filter(t=>t.deadline_type==='none'),completed:sorted.filter(t=>t.status==='completed')};}
export function calendarEvents(tasks:Task[],meetings:Meeting[],courses:Course[],semesters:Semester[],zone:string,start:string,end:string) {const first=Temporal.PlainDate.from(start),last=Temporal.PlainDate.from(end);if(Temporal.PlainDate.compare(first,last)>0||first.until(last).days>62)throw Error('Calendar range must be between 0 and 62 days');const events:{id:string;title:string;date:string;time:string|null;kind:string;course_id:string|null;task_id?:string}[]=[];for(const t of tasks){const date=dueDay(t,zone);if(date&&date>=start&&date<=end&&t.status!=='cancelled')events.push({id:t.id,title:t.title,date,time:t.due_at?Temporal.Instant.from(t.due_at).toZonedDateTimeISO(zone).toPlainTime().toString().slice(0,5):null,kind:t.type,course_id:t.course_id,task_id:t.id});}for(let day=first;Temporal.PlainDate.compare(day,last)<=0;day=day.add({days:1})){const date=day.toString();for(const m of meetings){const c=courses.find(c=>c.id===m.course_id);const sem=semesters.find(s=>s.id===c?.semester_id);if(!c||sem?.archived_at||day.dayOfWeek%7!==m.day_of_week||(m.start_date&&date<m.start_date)||(m.end_date&&date>m.end_date)||(sem?.start_date&&date<sem.start_date)||(sem?.end_date&&date>sem.end_date))continue;events.push({id:`${m.id}:${date}`,title:c.name,date,time:m.start_time.slice(0,5),kind:'class',course_id:c.id});}}return events.sort((a,b)=>a.date.localeCompare(b.date)||(a.time??'').localeCompare(b.time??''));}
