import 'server-only';
import { z } from 'zod';

export class HttpError extends Error {constructor(public status:number,public code:string,message:string){super(message);}}
export function check<T>(r:{data:T;error:{message:string;code?:string}|null}):NonNullable<T> {checkError(r.error);if(r.data===null||r.data===undefined)throw new HttpError(404,'NOT_FOUND','Record not found.');return r.data;}
export function optional<T>(r:{data:T;error:{message:string;code?:string}|null}):T {checkError(r.error);return r.data;}
export function checkError(error:{message:string;code?:string}|null){if(error){if(error.code==='23503'||error.code==='23514'||error.code==='22P02')throw new HttpError(400,'INVALID_REFERENCE','Check the record relationships and field values.');if(error.code==='42501')throw new HttpError(403,'FORBIDDEN','Access denied.');throw new HttpError(500,'DATABASE_ERROR','The database operation failed.');}}
export async function boundedBody(req:Request,max:number){const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new HttpError(413,'BODY_TOO_LARGE','Request is too large.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;}
export async function jsonBody(req:Request){const raw=new TextDecoder().decode(await boundedBody(req,100000));try{return JSON.parse(raw);}catch{throw new HttpError(400,'INVALID_JSON','Send valid JSON.');}}
export function response(data:unknown,status=200){return Response.json({data},{status,headers:{'Cache-Control':'no-store'}});}
export async function handled(req:Request,fn:()=>Promise<Response>){const request_id=crypto.randomUUID(),start=Date.now();let status=500;try{const res=await fn();status=res.status;res.headers.set('X-Request-Id',request_id);res.headers.set('Cache-Control','no-store');return res;}catch(e){status=e instanceof z.ZodError?400:e instanceof HttpError?e.status:500;const code=e instanceof z.ZodError?'VALIDATION_ERROR':e instanceof HttpError?e.code:'INTERNAL_ERROR';if(status>=500&&process.env.SENTRY_DSN){const Sentry=await import('@sentry/nextjs');Sentry.captureException(new Error(code),{tags:{request_id,route:new URL(req.url).pathname}});}return Response.json({error:{code,message:e instanceof z.ZodError?'Check the submitted fields.':e instanceof HttpError?e.message:'Something went wrong. Please retry.',request_id,...(e instanceof z.ZodError?{issues:e.issues.map(i=>({path:i.path,message:i.message}))}:{})}},{status,headers:{'Cache-Control':'no-store','X-Request-Id':request_id}});}finally{console.info(JSON.stringify({request_id,route:new URL(req.url).pathname,status,duration_ms:Date.now()-start}));}}
