import 'server-only';
import { adminClient, sessionClient } from '@/lib/supabase';
import { HttpError, check, optional, checkError } from '@/lib/http';
import { env } from '@/lib/env';
export async function authorize(req:Request){if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.get('origin')!==new URL(env().APP_ORIGIN).origin)throw new HttpError(403,'ORIGIN_DENIED','Request origin is not allowed.');const db=await sessionClient();const {data:{user},error}=await db.auth.getUser();if(error||!user)throw new HttpError(401,'UNAUTHENTICATED','Sign in to continue.');if(!user.email_confirmed_at||!user.identities?.some(i=>i.provider==='google')||!check(await db.rpc('is_beta_user')))throw new HttpError(403,'BETA_ACCESS_REQUIRED','This beta is limited to invited Google accounts.');return {db,user,admin:adminClient()};}
export type Context=Awaited<ReturnType<typeof authorize>>;
export async function ensureProfile(ctx:Context){let p=optional(await ctx.db.from('profiles').select('*').eq('id',ctx.user.id).maybeSingle());if(!p){p=optional(await ctx.admin.from('profiles').upsert({id:ctx.user.id,email:ctx.user.email!,display_name:String(ctx.user.user_metadata.full_name||'').slice(0,100)},{onConflict:'id',ignoreDuplicates:true}).select().maybeSingle());if(!p)p=check(await ctx.db.from('profiles').select('*').eq('id',ctx.user.id).single());}return p;}
export async function removeFiles(ctx:Context,paths:string[]){for(let i=0;i<paths.length;i+=100)check(await ctx.admin.storage.from('documents').remove(paths.slice(i,i+100)));}
export async function deleteAccount(ctx:Context,confirmation:string){if(confirmation!=='DELETE')throw new HttpError(400,'CONFIRMATION_REQUIRED','Type DELETE to confirm.');if(!ctx.user.last_sign_in_at||Date.now()-Date.parse(ctx.user.last_sign_in_at)>10*60*1000)throw new HttpError(403,'REAUTH_REQUIRED','Sign in with Google again before deleting your account.');optional(await ctx.admin.from('profiles').update({deleting_at:new Date().toISOString()}).eq('id',ctx.user.id));try{const docs=check(await ctx.admin.from('documents').select('storage_path').eq('owner_id',ctx.user.id));await removeFiles(ctx,docs.map(d=>d.storage_path));checkError((await ctx.admin.auth.admin.deleteUser(ctx.user.id)).error);await ctx.db.auth.signOut();}catch(e){await ctx.admin.from('profiles').update({deleting_at:null}).eq('id',ctx.user.id);throw e;}}
