import 'server-only';
import { z } from 'zod';
import { date, id as uuid, taskTypes } from '@/lib/contracts';
import { Temporal } from '@js-temporal/polyfill';
import { courseInput, meetingInput, semesterInput, taskInput, type Task, type Course, type Semester, type Meeting } from '@/lib/contracts';
import { check, optional, HttpError } from '@/lib/http';
import { removeFiles, type Context } from './accounts';
export const resources={semesters:semesterInput,courses:courseInput,tasks:taskInput,course_meetings:meetingInput};
export type Resource=keyof typeof resources;
export async function record(ctx:Context,table:Resource,id:string){const r=optional(await ctx.db.from(table).select('*').eq('id',id).maybeSingle());if(!r)throw new HttpError(404,'NOT_FOUND','Record not found.');return r;}
export async function list(ctx:Context,table:Resource,url:URL){const page=Math.max(0,Number(url.searchParams.get('page')||0)),limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')||50)));if(!Number.isInteger(page)||!Number.isInteger(limit))throw new HttpError(400,'INVALID_PAGE','Invalid pagination.');let q=ctx.db.from(table).select('*',{count:'exact'}).order('created_at',{ascending:false});if(table==='courses'&&url.searchParams.get('semester_id'))q=q.filter('semester_id','eq',url.searchParams.get('semester_id')!);if((table==='tasks'||table==='course_meetings')&&url.searchParams.get('course_id'))q=q.filter('course_id','eq',url.searchParams.get('course_id')!);if(table==='tasks'){
 const semester=url.searchParams.get('semester_id');if(semester){uuid.parse(semester);const cs=check(await ctx.db.from('courses').select('id').eq('semester_id',semester));q=q.filter('course_id','in',`(${cs.map(c=>c.id).join(',')||'00000000-0000-0000-0000-000000000000'})`);}
 const due=url.searchParams.get('date');if(due){date.parse(due);const profile=check(await ctx.db.from('profiles').select('timezone').eq('id',ctx.user.id).single());const day=Temporal.PlainDate.from(due),start=day.toZonedDateTime(profile.timezone).toInstant().toString(),end=day.add({days:1}).toZonedDateTime(profile.timezone).toInstant().toString();q=q.or(`due_date.eq.${due},and(due_at.gte.${start},due_at.lt.${end})`);}
 if(url.searchParams.get('status'))z.enum(['pending','completed','cancelled']).parse(url.searchParams.get('status'));
 if(url.searchParams.get('type'))z.enum(taskTypes).parse(url.searchParams.get('type'));
 for(const key of ['status','type'] as const){const v=url.searchParams.get(key);if(v)q=q.filter(key,'eq',v);}const search=url.searchParams.get('q');if(search)q=q.ilike('title',`%${search.replace(/[%_\\]/g,'')}%`);}if(table==='courses'&&url.searchParams.get('q'))q=q.ilike('name',`%${url.searchParams.get('q')!.replace(/[%_\\]/g,'')}%`);const r=await q.range(page*limit,page*limit+limit-1);check(r);return {items:r.data,total:r.count,page,limit};}
export async function write(ctx:Context,table:Resource,body:unknown,id?:string){
 if(id)await record(ctx,table,id);
 if(table==='tasks'){const p=taskInput.parse(body),data={...p,owner_id:ctx.user.id,completed_at:p.status==='completed'?new Date().toISOString():null};const row=check(id?await ctx.db.from('tasks').update(data).eq('id',id).select().single():await ctx.db.from('tasks').insert(data).select().single());if(!id||p.status==='completed')await ctx.admin.from('activity_events').insert({owner_id:ctx.user.id,event:p.status==='completed'?'task_completed':'task_created',entity_id:row.id});return row;}
 if(table==='courses'){const data={...courseInput.parse(body),owner_id:ctx.user.id};return check(id?await ctx.db.from('courses').update(data).eq('id',id).select().single():await ctx.db.from('courses').insert(data).select().single());}
 if(table==='semesters'){const data={...semesterInput.parse(body),owner_id:ctx.user.id};return check(id?await ctx.db.from('semesters').update(data).eq('id',id).select().single():await ctx.db.from('semesters').insert(data).select().single());}
 const data={...meetingInput.parse(body),owner_id:ctx.user.id};return check(id?await ctx.db.from('course_meetings').update(data).eq('id',id).select().single():await ctx.db.from('course_meetings').insert(data).select().single());
}
export async function remove(ctx:Context,table:Resource,id:string){await record(ctx,table,id);if(table==='semesters'||table==='courses'){let ids=[id];if(table==='semesters')ids=check(await ctx.db.from('courses').select('id').eq('semester_id',id)).map(c=>c.id);const documents=ids.length?check(await ctx.db.from('documents').select('storage_path').in('course_id',ids)):[];if(table==='semesters'){const imports=check(await ctx.db.from('imports').select('document_id').eq('semester_id',id));if(imports.length){const extra=check(await ctx.db.from('documents').select('id,storage_path').in('id',imports.map(i=>i.document_id)));await removeFiles(ctx,extra.map(d=>d.storage_path));optional(await ctx.admin.from('documents').delete().in('id',extra.map(d=>d.id)).eq('owner_id',ctx.user.id));}}await removeFiles(ctx,documents.map(d=>d.storage_path));}optional(await ctx.db.from(table).delete().eq('id',id));}
// Fetch complete private datasets in bounded database pages (no silent 1000-row truncation).
export async function allRows(ctx:Context,table:'tasks'|'courses'|'semesters'|'course_meetings'|'documents'|'imports'|'import_candidates'|'grading_components'|'course_policies'|'profiles') {const rows:Record<string,unknown>[]=[];for(let from=0;;from+=500){const batch=check(await ctx.db.from(table).select('*').order(table==='profiles'?'id':'created_at').range(from,from+499));rows.push(...batch);if(batch.length<500)break;}return rows;}
export async function academicData(ctx:Context,includeArchived=false){const [tasks,courses,semesters,meetings]=await Promise.all([allRows(ctx,'tasks'),allRows(ctx,'courses'),allRows(ctx,'semesters'),allRows(ctx,'course_meetings')]);const ss=semesters as unknown as Semester[],cs=courses as unknown as Course[];const active=new Set(cs.filter(c=>includeArchived||!ss.find(s=>s.id===c.semester_id)?.archived_at).map(c=>c.id));return {tasks:(tasks as unknown as Task[]).filter(t=>!t.course_id||active.has(t.course_id)),courses:cs.filter(c=>active.has(c.id)),semesters:ss,meetings:(meetings as unknown as Meeting[]).filter(m=>active.has(m.course_id))};}
