import 'server-only';
import { createHash } from 'node:crypto';
import { z } from 'zod';
import { check,optional,HttpError,boundedBody } from '@/lib/http';
import { id,candidateSchemas,reviewInput,type EntityType } from '@/lib/contracts';
import type { Json } from '@/lib/database.types';
import type { Context } from './accounts';
import { readPdf,normalize,OpenAIExtractionProvider,type SyllabusExtractionProvider } from './syllabus';
export async function upload(ctx:Context,req:Request){if(Number(req.headers.get('content-length')||0)>4400000)throw new HttpError(413,'FILE_TOO_LARGE','PDF limit is 4 MiB.');const uploadBytes=await boundedBody(req,4400000);const form=await new Response(uploadBytes,{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData(),file=form.get('file'),semester=id.parse(form.get('semester_id')),course=id.nullable().parse(form.get('course_id')||null);if(!(file instanceof File)||file.type!=='application/pdf'||file.size>4194304||file.size===0)throw new HttpError(400,'INVALID_FILE','Upload a PDF no larger than 4 MiB.');if(!optional(await ctx.db.from('semesters').select('id').eq('id',semester).maybeSingle()))throw new HttpError(404,'NOT_FOUND','Semester not found.');if(course&&!optional(await ctx.db.from('courses').select('id').eq('id',course).eq('semester_id',semester).maybeSingle()))throw new HttpError(400,'INVALID_COURSE','Choose a course in this semester.');const count=await ctx.db.from('documents').select('id',{count:'exact',head:true});optional(count);if((count.count||0)>=30)throw new HttpError(429,'DOCUMENT_LIMIT','Beta limit: 30 stored documents. Delete an old document before uploading.');const bytes=new Uint8Array(await file.arrayBuffer());await readPdf(bytes.slice());const hash=createHash('sha256').update(bytes).digest('hex');const duplicate=check(await ctx.db.from('documents').select('id').eq('sha256',hash).limit(1));if(duplicate.length&&form.get('allow_duplicate')!=='true')throw new HttpError(409,'DUPLICATE_DOCUMENT','This exact PDF is already uploaded. Review the existing import or explicitly upload another copy.');const docId=crypto.randomUUID(),path=`${ctx.user.id}/${docId}.pdf`;check(await ctx.admin.storage.from('documents').upload(path,bytes,{contentType:'application/pdf',upsert:false}));try{const doc=check(await ctx.admin.from('documents').insert({id:docId,owner_id:ctx.user.id,course_id:course,storage_path:path,original_filename:file.name.slice(0,200),mime_type:'application/pdf',size_bytes:file.size,sha256:hash}).select().single());const imp=check(await ctx.admin.from('imports').insert({owner_id:ctx.user.id,document_id:docId,semester_id:semester,course_id:course}).select().single());return {document:doc,import:imp};}catch(e){await ctx.admin.from('documents').delete().eq('id',docId);await ctx.admin.storage.from('documents').remove([path]);throw e;}}
export async function getImport(ctx:Context,importId:string){const r=optional(await ctx.db.from('imports').select('*').eq('id',importId).maybeSingle());if(!r)throw new HttpError(404,'NOT_FOUND','Import not found.');return r;}
export async function processImport(ctx:Context,importId:string,provider:SyllabusExtractionProvider=new OpenAIExtractionProvider()){await getImport(ctx,importId);const claim=await ctx.admin.rpc('claim_import',{p_id:importId,p_owner:ctx.user.id});if(claim.error)throw new HttpError(409,'IMPORT_BUSY_OR_LIMITED','Import unavailable, already running, or extraction limit reached (5 per hour; 5 attempts per import).');const imp=claim.data,start=Date.now();try{const doc=check(await ctx.db.from('documents').select('*').eq('id',imp.document_id).single());const blob=check(await ctx.admin.storage.from('documents').download(doc.storage_path));const pages=await readPdf(new Uint8Array(await blob.arrayBuffer()));const profile=check(await ctx.db.from('profiles').select('timezone').eq('id',ctx.user.id).single());const sem=check(await ctx.db.from('semesters').select('name').eq('id',imp.semester_id).single());const {result,metrics}=await provider.extract(pages,profile.timezone,sem.name);const candidates=normalize(result,pages);optional(await ctx.admin.rpc('save_candidates',{p_id:importId,p_owner:ctx.user.id,p_candidates:candidates as unknown as Json,p_result:result as unknown as Json,p_metrics:metrics}));console.info(JSON.stringify({event:'extraction',import_id:importId,...metrics,status:'needs_review'}));return {status:'needs_review',count:candidates.length};}catch(e){const error=e instanceof HttpError?e:new HttpError(502,'EXTRACTION_FAILED','Analysis failed. Your PDF is saved; please retry later.');await ctx.admin.from('imports').update({status:'failed',provider:'openai',model:process.env.OPENAI_MODEL||'gpt-4.1-mini',duration_ms:Date.now()-start,error_code:error.code,error_message:error.message,completed_at:new Date().toISOString()}).eq('id',importId).eq('status','processing');throw error;}}
export async function review(ctx:Context,importId:string,body:unknown){await getImport(ctx,importId);const input=reviewInput.parse(body),c=check(await ctx.db.from('import_candidates').select('*').eq('id',input.candidate_id).eq('import_id',importId).single());const parsed=candidateSchemas[c.entity_type as EntityType].parse(input.candidate_data);optional(await ctx.admin.rpc('review_candidate',{p_import:importId,p_owner:ctx.user.id,p_candidate:c.id,p_data:parsed as Json,p_accepted:input.accepted}));}
export async function confirm(ctx:Context,importId:string){const imp=await getImport(ctx,importId);if(imp.status==='confirmed')return {course_id:imp.course_id};const candidates=check(await ctx.db.from('import_candidates').select('*').eq('import_id',importId).eq('accepted',true));if(!candidates.length)throw new HttpError(400,'EMPTY_IMPORT','Select at least one item.');for(const c of candidates)candidateSchemas[c.entity_type as EntityType].parse(c.candidate_data);if(!imp.course_id&&!candidates.some(c=>c.entity_type==='course'&&z.object({name:z.string().min(1)}).safeParse(c.candidate_data).success))throw new HttpError(400,'COURSE_REQUIRED','Accept and name the course before confirming.');const r=await ctx.admin.rpc('confirm_import',{p_id:importId,p_owner:ctx.user.id});if(r.error)throw new HttpError(409,'CONFIRM_FAILED','Import could not be confirmed. Refresh and check the selected items.');return {course_id:r.data};}
