import 'server-only';
import { z } from 'zod';
import { authorize,ensureProfile,deleteAccount,removeFiles } from './accounts';
import { resources,list,record,write,remove,academicData,allRows,type Resource } from './coursework';
import { upload,getImport,processImport,review,confirm } from './documents';
import { check,optional,HttpError,jsonBody,response } from '@/lib/http';
import { id,date,onboardingInput,profileInput } from '@/lib/contracts';
import { dashboard,calendarEvents,todayIn } from '@/lib/dates';
import { exportAccount } from './export';
export async function route(req:Request,path:string[]){const ctx=await authorize(req),url=new URL(req.url),[family,rawId,action]=path,method=req.method;const key=rawId?id.parse(rawId):undefined;const profile=await ensureProfile(ctx);
 if(family==='me'){if(method==='GET')return response(profile);if(method==='PATCH'){const body=profileInput.parse(await jsonBody(req));return response(check(await ctx.admin.from('profiles').update(body).eq('id',ctx.user.id).select().single()));}if(method==='DELETE'){await deleteAccount(ctx,z.object({confirmation:z.literal('DELETE')}).parse(await jsonBody(req)).confirmation);return response({deleted:true});}}
 if(family==='onboarding'&&method==='POST'){const b=onboardingInput.parse(await jsonBody(req));optional(await ctx.admin.rpc('complete_onboarding',{p_owner:ctx.user.id,p_email:ctx.user.email!,p_name:b.display_name,p_timezone:b.timezone,p_semester:b.semester_name}));return response({completed:true});}
 if(family==='export'&&method==='GET')return exportAccount(ctx,z.enum(['json','csv']).parse(url.searchParams.get('format')||'json'));
 if((family==='dashboard'||family==='calendar')&&method==='GET'){const data=await academicData(ctx);await ctx.admin.from('activity_events').insert({owner_id:ctx.user.id,event:family==='dashboard'?'dashboard_view':'calendar_view'});if(family==='calendar'){const start=date.parse(url.searchParams.get('start')),end=date.parse(url.searchParams.get('end'));try{return response(calendarEvents(data.tasks,data.meetings,data.courses,data.semesters,profile.timezone,start,end));}catch{throw new HttpError(400,'INVALID_RANGE','Choose a calendar range of 62 days or less.');}}const today=todayIn(profile.timezone);return response({...dashboard(data.tasks,profile.timezone),classes:calendarEvents([],data.meetings,data.courses,data.semesters,profile.timezone,today,today),courses:data.courses});}
 if(family==='courses'&&key&&action==='meetings'){await record(ctx,'courses',key);if(method==='GET'){url.searchParams.set('course_id',key);return response(await list(ctx,'course_meetings',url));}if(method==='POST')return response(await write(ctx,'course_meetings',{...await jsonBody(req),course_id:key}),201);}
 if(family==='courses'&&key&&action==='details'&&method==='GET'){await record(ctx,'courses',key);return response({grading:check(await ctx.db.from('grading_components').select('*').eq('course_id',key)),policies:check(await ctx.db.from('course_policies').select('*').eq('course_id',key)),meetings:check(await ctx.db.from('course_meetings').select('*').eq('course_id',key))});}
 if(family in resources&&!action){const table=family as Resource;if(method==='GET')return response(key?await record(ctx,table,key):await list(ctx,table,url));if(method==='POST'&&!key)return response(await write(ctx,table,await jsonBody(req)),201);if(method==='PATCH'&&key){const existing=await record(ctx,table,key),body=await jsonBody(req);const keys=Object.keys(resources[table].parse(Object.fromEntries(Object.entries(existing).filter(([k])=>!['id','owner_id','created_at','updated_at','completed_at','source_type','source_id','source_document_id','source_page','source_excerpt','confidence','lms_provider','lms_course_id','lms_url'].includes(k)))));const clean=Object.fromEntries(Object.entries(existing).filter(([k])=>keys.includes(k)));return response(await write(ctx,table,{...clean,...body},key));}if(method==='DELETE'&&key){z.object({confirmation:z.literal('DELETE')}).parse(await jsonBody(req));await remove(ctx,table,key);return response({deleted:true});}}
 if(family==='documents'){if(method==='POST'&&!key)return response(await upload(ctx,req),201);if(method==='GET'&&!key)return response(await allRows(ctx,'documents'));if(key){const doc=optional(await ctx.db.from('documents').select('*').eq('id',key).maybeSingle());if(!doc)throw new HttpError(404,'NOT_FOUND','Document not found.');if(method==='GET'){const file=check(await ctx.admin.storage.from('documents').createSignedUrl(doc.storage_path,60,{download:doc.original_filename}));return response({...doc,url:file.signedUrl});}if(method==='DELETE'){z.object({confirmation:z.literal('DELETE')}).parse(await jsonBody(req));await removeFiles(ctx,[doc.storage_path]);optional(await ctx.admin.from('documents').delete().eq('id',key).eq('owner_id',ctx.user.id));return response({deleted:true});}}}
 if(family==='imports'){if(method==='GET'&&!key){const rows=await allRows(ctx,'imports');return response(rows.map(({raw_result: _raw,normalized_result: _normalized,...r})=>{void _raw;void _normalized;return r;}));}if(key){if(method==='GET'){const imp=await getImport(ctx,key);return response({...imp,candidates:check(await ctx.db.from('import_candidates').select('*').eq('import_id',key).order('created_at'))});}if(method==='POST'&&action==='process')return response(await processImport(ctx,key));if(method==='PATCH'&&action==='review'){await review(ctx,key,await jsonBody(req));return response({saved:true});}if(method==='POST'&&action==='confirm')return response(await confirm(ctx,key));}}
 throw new HttpError(404,'NOT_FOUND','Endpoint not found.');
}
