import {writeFileSync} from 'node:fs';
import {z} from 'zod';
import {profileInput,onboardingInput,semesterInput,courseInput,taskInput,meetingInput,reviewInput} from '../src/lib/contracts';
const schemas={ProfileInput:profileInput,OnboardingInput:onboardingInput,SemesterInput:semesterInput,CourseInput:courseInput,TaskInput:taskInput,MeetingInput:meetingInput,ReviewInput:reviewInput};
const components=Object.fromEntries(Object.entries(schemas).map(([k,v])=>[k,z.toJSONSchema(v)]));
const paths:Record<string,Record<string,unknown>>={};
function op(path:string,method:string,summary:string,input?:string){paths[path]??={};paths[path][method]={summary,security:[{supabaseSession:[]}],...(path.includes('{id}')?{parameters:[{name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}}]}:{}),...(input?{requestBody:{required:true,content:{'application/json':{schema:{$ref:`#/components/schemas/${input}`}}}}}:{}),responses:{'200':{description:'Success. JSON response is wrapped in {data: ...}, except downloads.'},'400':{description:'Invalid request'},'401':{description:'Missing or expired session'},'403':{description:'Beta access denied or invalid Origin'},'404':{description:'Not found or not owned'},'409':{description:'Conflict or import state/limit restriction'},'500':{description:'Operation failed; use error.request_id for support'}}};}
for(const [name,schema] of [['semesters','SemesterInput'],['courses','CourseInput'],['tasks','TaskInput'],['course_meetings','MeetingInput']]){op(`/${name}`,'get',`List ${name}; page starts at 0, limit 1–100`);op(`/${name}`,'post',`Create ${name}`,schema);op(`/${name}/{id}`,'get',`Read ${name}`);op(`/${name}/{id}`,'patch',`Update ${name}; partial fields accepted`);op(`/${name}/{id}`,'delete','Permanently delete; body requires confirmation: DELETE');}
op('/me','get','Read profile');op('/me','patch','Update profile','ProfileInput');op('/me','delete','Delete account and files; recent login and confirmation: DELETE required');op('/onboarding','post','Idempotent onboarding','OnboardingInput');op('/courses/{id}/details','get','Course meetings, grading, and policies');op('/courses/{id}/meetings','get','List course meetings');op('/courses/{id}/meetings','post','Create course meeting','MeetingInput');op('/dashboard','get','Active coursework grouped by urgency; classes today');op('/calendar','get','Expanded class meetings and tasks; required start/end ISO dates, max 62 days');op('/export','get','Private JSON/CSV download; format=json|csv');op('/documents','get','List document metadata');op('/documents','post','Upload multipart PDF: file, semester_id, optional course_id/allow_duplicate; 4 MiB limit');op('/documents/{id}','get','Metadata and 60-second private download URL');op('/documents/{id}','delete','Delete file/import drafts; keep confirmed coursework');op('/imports','get','List imports');op('/imports/{id}','get','Import and review candidates');op('/imports/{id}/process','post','Analyze or retry saved PDF');op('/imports/{id}/review','patch','Save candidate changes/selection','ReviewInput');op('/imports/{id}/confirm','post','Atomically confirm accepted items; idempotent');
writeFileSync('docs/openapi.json',JSON.stringify({openapi:'3.1.0',info:{title:'StayDue V1',version:'0.1.0'},servers:[{url:'/api/v1'}],paths,components:{schemas:components,securitySchemes:{supabaseSession:{type:'apiKey',in:'cookie',name:'sb-<project>-auth-token',description:'Managed by @supabase/ssr; cookie may be split into chunks. Browser mutations require same-origin Origin header.'}}}},null,2)+'\n');
